version: "3.7"

services:
  database:
    build:
      args:
        base_image: mysql:8.0.15
      context: ./database
      dockerfile: ./Dockerfile.local
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    networks:
      - back-end
    ports:
      - "3306:3306"
    secrets:
      - mysql_root_password
    security_opt:
      - seccomp:unconfined
  dotnetcore-api:
    build:
      args:
        build_image: microsoft/dotnet:2.2.104-sdk-alpine3.8
        base_image: microsoft/dotnet:2.2.2-aspnetcore-runtime-alpine3.8
      context: ./dotnetcore-api
      dockerfile: ./Dockerfile.local
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Local
    networks:
      - back-end
      - front-end
    ports:
      - "57989:80"
  java-app:
    build:
      args:
        build_image: maven:latest
        base_image: tomcat:7-jre8
      context: ./java-app
      dockerfile: ./Dockerfile.local
    depends_on:
      - dotnetcore-api
    environment:
      BASEURI: http://dotnetcore-api/api/users
    networks:
      - front-end
    ports:
      - "8080:8080"

networks:
    back-end:
    front-end:

secrets:
    mysql_root_password:
        file: secrets/mysql_root_password
