version: "3.3"

services:

  database:
    image: database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password 
    # Expose port 3306 to host. 
    ports:
      - "3306:3306" 
    networks:
      - back-tier

  java-app:
    image: java-app-v2
    environment:
      BASEURI: http://dotnet-api/api/users
    ports:
      - "8080:8080" 
      - "8000:8000"
    networks:
      - front-tier
      - back-tier

  dotnet-api:
    image: dotnet-api
    ports:
      - "57989:80"
    networks:
      - front-tier
      - back-tier

networks:
  back-tier:
  front-tier:

secrets:
  mysql_password:
    file: ./secrets/mysql_password